### PR TITLE
After initial generation of my app, I was confused to find the tests would not run.

### PR DESCRIPTION
**Pull request by davetheninja**
...s = true

### CODE REVIEW

**Comment by ahawkins** [comment]
Great catch! Can you remove the changes to gitignore?

**Comment by davetheninja** [comment]
After initial generation of my app, I was confused to find the tests would not run. I did some digging and found the setting to enable test generation when compiling.

It seems like a minor oversight.

**Comment by davetheninja** [comment]
@ahawkins sure thing.  Ill do that now

**Comment by ahawkins** [comment]
I can't merge this. You need to rebase it off master.

**Comment by davetheninja** [comment]
on it!

**Pull request merged**
