### PR TITLE
Sass / SCSS Partials in subdirectories should not be compiled

### PR DESCRIPTION
**Pull request by heycarsten**

### CODE REVIEW

**Comment by heycarsten** [comment]
Aww shit, I didn't notice the whitespace stuff. I can make a new PR if it matters to you.

**Comment by ahawkins** [comment]
I don't mind the whitespace. The PR cannot be merged automatically. Rebase your stuff against master. Thanks for finding bugs. 

Do you think it make sense to make `stylesheets/partials`?

**Comment by heycarsten** [comment]
@twinturbo I fixed the conflict and renamed /subdir to /partials in the test cases. Should be good to go.

**Comment by heycarsten** [comment]
I see you fixed this upstream.

**Comment by ahawkins** [comment]
Ya I totally forgot about this. `skip` + `match` is much cleaner now. Sorry it took so long. :/

**Pull request closed without merging**
